/**
 * Verdant Greens - Central Product Catalog
 * Location: Ndola, Copperbelt Province, Zambia
 * Currency: ZMW (Zambian Kwacha - K)
 * Live On-Sale Price Range: K400 - K1,200
 */

const PRODUCTS = [
    {
        id: 'vg-s01',
        name: 'The Greenhouse Grand Masterpiece',
        botanicalName: 'Monstera Deliciosa & Palm Hybrid Specimen',
        category: 'statement',
        price: 1200,
        image: 'images/products/the-greenhouse-masterpiece-k1200.webp',
        badge: 'Premier Statement',
        badgeColor: 'var(--verdant-primary)',
        light: 'Bright Indirect Light',
        water: 'Every 7-10 Days',
        petFriendly: false,
        size: 'Extra Large (1.2m - 1.4m)',
        description: 'Our crown jewel statement piece. Towering, lush architectural foliage meticulously acclimatized in our Ndola greenhouse to be the stunning centerpiece of your luxury home or executive foyer.',
        featured: true,
        tags: ['masterpiece', 'monstera', 'grand', 'statement', 'premier', 'ndola', 'large', 'foyer']
    },
    {
        id: 'vg-s02',
        name: 'Anthurium Giant Exotic Statement Specimen',
        botanicalName: 'Anthurium Hookeri Grandis',
        category: 'rare',
        price: 1100,
        image: 'images/products/anthurium-statement-pot-k1100.webp',
        badge: 'Rare Exotic',
        badgeColor: 'var(--cerulean-primary)',
        light: 'Bright Filtered Light',
        water: 'Every 5-7 Days',
        petFriendly: false,
        size: 'Extra Large (1.1m)',
        description: 'Huge undulating paddle leaves with ruffled edges. A breathtaking luxury centerpiece grown with greenhouse care in Ndola, perfect for well-lit living spaces.',
        featured: true,
        tags: ['anthurium', 'exotic', 'rare', 'statement', 'luxury', 'grand', 'foliage', 'flowering']
    },
    {
        id: 'vg-s03',
        name: 'Architectural Giant Agave Grand Specimen',
        botanicalName: 'Agave Americana Marginata',
        category: 'statement',
        price: 1000,
        image: 'images/products/architectural-giant-agave-k1000.webp',
        badge: 'Rare Focal Point',
        badgeColor: 'var(--cerulean-primary)',
        light: 'Bright Sun to Window Light',
        water: 'Every 3-4 Weeks',
        petFriendly: false,
        size: 'Extra Large (1.0m - 1.2m)',
        description: 'Striking structural form with thick, sculpted variegated blue-green leaves. Exceptionally resilient, drought-hardy, and brings dramatic modern botanical aesthetics to bright rooms.',
        featured: true,
        tags: ['agave', 'giant', 'statement', 'premier', 'focal point', 'desert', 'drought hardy']
    },
    {
        id: 'vg-s04',
        name: "King George's Royal Sword Grand Specimen",
        botanicalName: 'Sansevieria Stuckyi Grandis',
        category: 'statement',
        price: 1000,
        image: 'images/products/king-georges-royal-sword-grand-k1000.webp',
        badge: 'Top Air Purifier',
        badgeColor: 'var(--verdant-dark)',
        light: 'Low to Bright Indirect',
        water: 'Every 14-20 Days',
        petFriendly: false,
        size: 'Extra Large (1.1m)',
        description: 'Towering cylindrical foliage with majestic vertical presence. Renowned for filtering airborne toxins overnight while tolerating lower light levels and minimal watering.',
        featured: false,
        tags: ['sansevieria', 'king george', 'statement', 'air purifier', 'tall', 'bedroom', 'low maintenance']
    },
    {
        id: 'vg-s05',
        name: 'Greenhouse Botanical Trio Bundle',
        botanicalName: 'Monstera, Aglaonema & Succulent Trio',
        category: 'bundle',
        price: 1000,
        image: 'images/products/greenhouse-grand-trio-bundle-k1000.webp',
        badge: 'Triple Bundle (Save 25%)',
        badgeColor: 'var(--coral-accent)',
        light: 'Medium to Bright Indirect',
        water: 'Weekly',
        petFriendly: false,
        size: 'Three-Pot Suite',
        description: 'Instant interior makeover suite containing three distinct foliage heights and textures ready to transform any living space or executive office.',
        featured: true,
        tags: ['bundle', 'trio', 'botanical suite', 'savings', 'greenhouse', 'potted', 'combo']
    },
    {
        id: 'vg-s06',
        name: 'Monstera Deliciosa (Swiss Cheese Plant)',
        botanicalName: 'Monstera Deliciosa',
        category: 'indoor',
        price: 950,
        image: 'images/products/monstera-deliciosa-swiss-cheese-k950.webp',
        badge: 'Jungle Icon',
        badgeColor: 'var(--verdant-primary)',
        light: 'Medium to Bright Indirect',
        water: 'Every 7-10 Days',
        petFriendly: false,
        size: 'Large (85cm)',
        description: 'Iconic fenestrated split leaves that epitomize lush botanical living. Vigorous grower that thrives in warm Zambian room temperatures.',
        featured: true,
        tags: ['monstera', 'swiss cheese', 'iconic', 'indoor', 'jungle', 'fenestrated', 'living room']
    },
    {
        id: 'vg-s07',
        name: 'Deluxe Air-Purifier & Succulent Duo Bundle',
        botanicalName: 'Sansevieria & Aglaonema Potted Pair',
        category: 'bundle',
        price: 950,
        image: 'images/products/deluxe-air-purifier-duo-bundle-k950.webp',
        badge: 'Curated Bundle (Save 20%)',
        badgeColor: 'var(--coral-accent)',
        light: 'Medium Indirect Light',
        water: 'Bi-Weekly',
        petFriendly: false,
        size: 'Dual Potted Ensemble',
        description: 'Harmonious two-plant starter bundle: one upright air-cleansing sword plant and one lush variegated bush in matching planters.',
        featured: true,
        tags: ['bundle', 'duo', 'air purifier', 'combo', 'value', 'potted', 'starter']
    },
    {
        id: 'vg-s08',
        name: "Traveller's Palm Architectural Specimen",
        botanicalName: 'Ravenala Madagascariensis',
        category: 'statement',
        price: 900,
        image: 'images/products/travellers-palm-specimen-k900.webp',
        badge: 'Tropical Grandeur',
        badgeColor: 'var(--verdant-primary)',
        light: 'Bright Light to Gentle Sun',
        water: 'Weekly',
        petFriendly: true,
        size: 'Large (90cm - 1.1m)',
        description: 'Symmetrical fan-like leaf arrangement reminiscent of exotic coastal paradises. Acclimatized in our Ndola greenhouse for bright interior spots.',
        featured: true,
        tags: ['travellers palm', 'fan palm', 'statement', 'tropical', 'pet friendly', 'large']
    },
    {
        id: 'vg-s09',
        name: 'Sculptural Variegated Desert Agave',
        botanicalName: 'Agave Americana Variegata',
        category: 'statement',
        price: 900,
        image: 'images/products/sculptural-agave-americana-k900.webp',
        badge: 'Drought Royalty',
        badgeColor: 'var(--cerulean-primary)',
        light: 'Bright Sunlight / Direct',
        water: 'Monthly',
        petFriendly: false,
        size: 'Large (85cm)',
        description: 'Thick, rosette leaves bordered in bold creamy gold. Brings modern desert luxury to bright entrance halls, verandas, and sunrooms.',
        featured: false,
        tags: ['agave', 'variegated', 'desert', 'sculptural', 'drought hardy', 'statement']
    },
    {
        id: 'vg-s10',
        name: 'Anthurium Hookeri Pink Blossom Exotic',
        botanicalName: 'Anthurium Hookeri Hybrid',
        category: 'rare',
        price: 850,
        image: 'images/products/anthurium-hookeri-pink-blossom-k850.webp',
        badge: 'Rare Collector',
        badgeColor: 'var(--cerulean-primary)',
        light: 'Bright Filtered Light',
        water: 'Every 5-7 Days',
        petFriendly: false,
        size: 'Large (70cm)',
        description: 'Captivating ruffled tropical specimen with subtle pastel pink floral inflorescence. High humidity lover that thrives indoors in Ndola.',
        featured: true,
        tags: ['anthurium', 'pink', 'rare', 'collector', 'blooms', 'exotic', 'ruffled']
    },
    {
        id: 'vg-s11',
        name: 'Zamioculcas Zamiifolia (ZZ / Zizi Plant)',
        botanicalName: 'Zamioculcas Zamiifolia',
        category: 'office',
        price: 850,
        image: 'images/products/zamioculcas-zizi-emerald-k850.webp',
        badge: 'Nearly Indestructible',
        badgeColor: 'var(--cerulean-accent)',
        light: 'Any Light (Deep Shade to Bright)',
        water: 'Every 14-21 Days',
        petFriendly: false,
        size: 'Medium (60cm)',
        description: 'Waxy, mirror-gloss leaves that store water in underground tubers. The gold standard of low-maintenance indoor plants for busy professionals.',
        featured: true,
        tags: ['zz plant', 'zizi', 'indestructible', 'low light', 'drought hardy', 'office', 'shade']
    },
    {
        id: 'vg-s12',
        name: 'Sansevieria Stuckyi Grandis Column',
        botanicalName: 'Sansevieria Stuckyi',
        category: 'statement',
        price: 850,
        image: 'images/products/sansevieria-stuckyi-grandis-k850.webp',
        badge: 'Architectural Peak',
        badgeColor: 'var(--verdant-dark)',
        light: 'Low to Full Sun',
        water: 'Every 14-20 Days',
        petFriendly: false,
        size: 'Large (80cm)',
        description: 'Heavy, deeply ribbed solid cylindrical tusks with immense structural presence. An extraordinary focal point for upscale interiors.',
        featured: false,
        tags: ['sansevieria', 'stuckyi', 'architectural', 'tusks', 'statement', 'air purifier']
    },
    {
        id: 'vg-s13',
        name: 'Sweet Berry Bush Greenhouse Specimen',
        botanicalName: 'Ardisia Crenata Coral Berry',
        category: 'indoor',
        price: 850,
        image: 'images/products/sweet-berry-bush-grand-k850.webp',
        badge: 'Lush Decorative',
        badgeColor: 'var(--verdant-accent)',
        light: 'Medium to Bright Indirect',
        water: 'Weekly',
        petFriendly: true,
        size: 'Medium (60cm)',
        description: 'Neat, scalloped dark foliage producing ornamental berry clusters. Adds refined organic charm to home dining rooms and kitchen counters.',
        featured: false,
        tags: ['berry bush', 'ardisia', 'pet friendly', 'decorative', 'indoor shrub', 'berries']
    },
    {
        id: 'vg-s14',
        name: 'Grand Croton Petra Fire',
        botanicalName: 'Codiaeum Variegatum Petra',
        category: 'indoor',
        price: 800,
        image: 'images/products/croton-petra-fire-k800.webp',
        badge: 'Fiery Autumn Colors',
        badgeColor: 'var(--coral-accent)',
        light: 'Bright Direct / Indirect',
        water: 'Every 5-7 Days',
        petFriendly: false,
        size: 'Large (70cm)',
        description: 'Broad, dramatic leaves painted with brilliant veins of crimson, canary yellow, and emerald green. A true visual spectacle in sunny rooms.',
        featured: true,
        tags: ['croton', 'petra', 'colorful', 'bright light', 'statement', 'accent', 'living room']
    },
    {
        id: 'vg-s15',
        name: 'Spathiphyllum Golden Mint Peace Lily',
        botanicalName: 'Spathiphyllum Variegata',
        category: 'indoor',
        price: 800,
        image: 'images/products/spathiphyllum-mint-peace-lily-k800.webp',
        badge: 'Flowering Purifier',
        badgeColor: 'var(--verdant-primary)',
        light: 'Low to Bright Indirect',
        water: 'Weekly (keep moist)',
        petFriendly: false,
        size: 'Medium (60cm)',
        description: 'Lush variegated emerald foliage with pristine white spathe blooms. Excellent for improving indoor humidity and bedroom air quality.',
        featured: true,
        tags: ['peace lily', 'spathiphyllum', 'flowering', 'variegated', 'air purifier', 'bedroom']
    },
    {
        id: 'vg-s16',
        name: 'Ficus Elastica Burgundy Rubber Tree',
        botanicalName: 'Ficus Elastica Abidjan',
        category: 'indoor',
        price: 800,
        image: 'images/products/ficus-elastica-burgundy-k800.webp',
        badge: 'Glossy Royal',
        badgeColor: 'var(--verdant-dark)',
        light: 'Medium to Bright Indirect',
        water: 'Weekly',
        petFriendly: false,
        size: 'Large (75cm)',
        description: 'Thick, leathery leaves with a deep wine-burgundy sheen. Stately indoor tree that makes a bold aesthetic statement.',
        featured: false,
        tags: ['rubber tree', 'ficus', 'burgundy', 'glossy', 'indoor tree', 'living room']
    },
    {
        id: 'vg-s17',
        name: 'Aglaonema Silver Frost Deluxe',
        botanicalName: 'Aglaonema Silver Frost',
        category: 'office',
        price: 800,
        image: 'images/products/aglaonema-silver-frost-k800.webp',
        badge: 'Executive Choice',
        badgeColor: 'var(--cerulean-primary)',
        light: 'Low to Medium Light',
        water: 'Every 7-10 Days',
        petFriendly: false,
        size: 'Medium-Large (65cm)',
        description: 'Dense canopy of frosty silver and jade leaves. Excellent for corporate boardrooms, lobbies, and reading lounges.',
        featured: false,
        tags: ['aglaonema', 'silver frost', 'corporate', 'office', 'shade', 'low maintenance']
    },
    {
        id: 'vg-s18',
        name: "Anthurium Hookeri Bird's Nest",
        botanicalName: 'Anthurium Hookeri',
        category: 'rare',
        price: 750,
        image: 'images/products/anthurium-hookeri-ruffled-k750.webp',
        badge: 'Exotic Foliage',
        badgeColor: 'var(--cerulean-primary)',
        light: 'Bright Filtered Light',
        water: 'Every 5-7 Days',
        petFriendly: false,
        size: 'Medium (55cm)',
        description: "Magnificent ruffled undulating foliage forming a striking botanical bird's nest rosette. Thrives in warm indoor spaces.",
        featured: true,
        tags: ['anthurium', 'hookeri', 'exotic', 'rare', 'foliage', 'statement']
    },
    {
        id: 'vg-s19',
        name: 'Ruay Sub Grand Potted Centerpiece',
        botanicalName: 'Aglaonema Costatum Variegata',
        category: 'office',
        price: 750,
        image: 'images/products/ruay-sub-grand-tabletop-k750.webp',
        badge: 'Tabletop Crown',
        badgeColor: 'var(--amber-accent)',
        light: 'Medium Indirect',
        water: 'Weekly',
        petFriendly: false,
        size: 'Medium (50cm)',
        description: 'Full, lushly branched prosperity plant in a sturdy decorative nursery planter. Brings positive energy to executive offices.',
        featured: false,
        tags: ['ruay sub', 'centerpiece', 'office', 'tabletop', 'prosperity']
    },
    {
        id: 'vg-s20',
        name: "King George's Cylindrical Sword",
        botanicalName: 'Sansevieria Cylindrica',
        category: 'statement',
        price: 700,
        image: 'images/products/king-george-sword-cylindrica-k700.webp',
        badge: 'Architectural',
        badgeColor: 'var(--verdant-dark)',
        light: 'Low to Bright Indirect',
        water: 'Every 14-20 Days',
        petFriendly: false,
        size: 'Medium-Large (60cm)',
        description: 'Smooth, upright spear-like cylindrical foliage. Gives a sophisticated modern minimalist look to contemporary living spaces.',
        featured: false,
        tags: ['sansevieria', 'cylindrica', 'architectural', 'modern', 'air purifier']
    },
    {
        id: 'vg-s21',
        name: 'Aglaonema Silver Queen Potted Specimen',
        botanicalName: 'Aglaonema Silver Queen',
        category: 'indoor',
        price: 700,
        image: 'images/products/aglaonema-focal-specimen-k700.webp',
        badge: 'Best Seller',
        badgeColor: 'var(--verdant-primary)',
        light: 'Low to Medium Indirect',
        water: 'Every 7-10 Days',
        petFriendly: false,
        size: 'Medium (50cm)',
        description: 'Broad variegated spearhead leaves. One of the top ten NASA clean-air plants for removing household airborne toxins.',
        featured: true,
        tags: ['aglaonema', 'silver queen', 'air purifier', 'living room', 'indoor', 'bestseller']
    },
    {
        id: 'vg-s22',
        name: 'Graceful Bamboo Palm Specimen',
        botanicalName: 'Chamaedorea Seifrizii',
        category: 'statement',
        price: 600,
        image: 'images/products/bamboo-palm-k600.webp',
        badge: 'Lush Tropical',
        badgeColor: 'var(--verdant-primary)',
        light: 'Medium to Bright Indirect',
        water: 'Weekly',
        petFriendly: true,
        size: 'Large (90cm - 1.1m)',
        description: 'Feathery clustering fronds that bring a calm tropical atmosphere. Non-toxic to cats and dogs, and a top-rated natural humidifier.',
        featured: true,
        tags: ['palm', 'bamboo', 'pet friendly', 'statement', 'living room', 'tropical']
    },
    {
        id: 'vg-s23',
        name: 'Ruay Sub Prosperity Bush',
        botanicalName: 'Aglaonema Costatum Foxii',
        category: 'office',
        price: 600,
        image: 'images/products/ruay-sub-prosperity-k600.webp',
        badge: 'Good Fortune',
        badgeColor: 'var(--amber-accent)',
        light: 'Medium Indirect Light',
        water: 'Weekly',
        petFriendly: false,
        size: 'Medium (40cm)',
        description: 'Known as the prosperity plant. Densely clustered dark leaves with bright white midribs and specks, potted in rich Ndola soil.',
        featured: true,
        tags: ['prosperity', 'ruay sub', 'aglaonema', 'office', 'tabletop', 'potted']
    },
    {
        id: 'vg-s24',
        name: 'Croton Mammy Spiral Twist',
        botanicalName: 'Codiaeum Variegatum Mammy',
        category: 'indoor',
        price: 600,
        image: 'images/products/croton-mammy-spiral-k600.webp',
        badge: 'Vivid Crimson',
        badgeColor: 'var(--coral-accent)',
        light: 'Bright Sunlight / Indirect',
        water: 'Every 5-7 Days',
        petFriendly: false,
        size: 'Medium (45cm)',
        description: 'Corkscrew-curling leaves featuring electric red, orange, and emerald tones. Perfect for warm, sunny balconies and sunny rooms.',
        featured: false,
        tags: ['croton', 'spiral', 'red', 'bright sun', 'accent', 'indoor']
    },
    {
        id: 'vg-s25',
        name: 'Aglaonema Emerald Beauty',
        botanicalName: 'Aglaonema Maria',
        category: 'office',
        price: 600,
        image: 'images/products/aglaonema-emerald-beauty-k600.webp',
        badge: 'Low Light Pro',
        badgeColor: 'var(--verdant-accent)',
        light: 'Low to Medium Indirect',
        water: 'Every 8-12 Days',
        petFriendly: false,
        size: 'Medium (40cm)',
        description: 'Rich dark green leaves with silvery-gray chevron patterns. Incredibly resilient to fluctuating indoor temperatures.',
        featured: false,
        tags: ['aglaonema', 'emerald', 'office', 'shade', 'desk', 'easy care']
    },
    {
        id: 'vg-s26',
        name: 'Desert Succulent & Cactus Potted Duo',
        botanicalName: 'Echinocactus & Haworthia Ensemble',
        category: 'succulent',
        price: 600,
        image: 'images/products/desert-succulent-trio-k600.webp',
        badge: 'Water Saver',
        badgeColor: 'var(--cerulean-accent)',
        light: 'Bright Sun to Window Light',
        water: 'Every 3 Weeks',
        petFriendly: true,
        size: 'Compact Potted Duo',
        description: 'Sculptural desert pair nestled in custom well-draining mineral potting mix. Needs watering only once or twice a month.',
        featured: false,
        tags: ['cactus', 'succulent', 'water saver', 'sun', 'windowsill', 'drought hardy']
    },
    {
        id: 'vg-s27',
        name: 'Sansevieria Zeylanica Bowstring',
        botanicalName: 'Dracaena Zeylanica',
        category: 'indoor',
        price: 550,
        image: 'images/products/sansevieria-zeylanica-k550.webp',
        badge: 'Top Air Purifier',
        badgeColor: 'var(--verdant-dark)',
        light: 'Low to High Indirect',
        water: 'Every 14-21 Days',
        petFriendly: false,
        size: 'Medium (45cm)',
        description: 'Classic sword-shaped leaves with deep green horizontal zig-zag stripes. Releases oxygen at night, perfect for bedrooms.',
        featured: true,
        tags: ['snake plant', 'sansevieria', 'bedroom', 'air purifier', 'low light', 'hardy']
    },
    {
        id: 'vg-s28',
        name: 'Potted Croton Gold Dust',
        botanicalName: 'Codiaeum Variegatum Punctatum',
        category: 'indoor',
        price: 500,
        image: 'images/products/croton-gold-dust-k500.webp',
        badge: 'Vibrant Foliage',
        badgeColor: 'var(--coral-accent)',
        light: 'Bright Indirect to Sunny',
        water: 'Every 5-7 Days',
        petFriendly: false,
        size: 'Compact (35cm)',
        description: 'Dappled golden speckles across leathery emerald leaves that add an energetic splash of tropical sunshine to bright rooms.',
        featured: true,
        tags: ['croton', 'gold', 'colorful', 'bright light', 'living room', 'potted']
    },
    {
        id: 'vg-s29',
        name: 'Silver Bay Aglaonema Compact',
        botanicalName: 'Aglaonema Commutatum Silver',
        category: 'office',
        price: 500,
        image: 'images/products/silver-aglaonema-compact-k500.webp',
        badge: 'Shade Tolerant',
        badgeColor: 'var(--verdant-primary)',
        light: 'Low to Medium Light',
        water: 'Every 7-10 Days',
        petFriendly: false,
        size: 'Compact (30cm)',
        description: 'Renowned silver-patterned foliage ideal for low-light corridors, study desks, and climate-controlled workspaces.',
        featured: false,
        tags: ['aglaonema', 'silver', 'shade', 'desk', 'office', 'air purifier']
    },
    {
        id: 'vg-s30',
        name: 'Sansevieria Compacta Dwarf',
        botanicalName: 'Sansevieria Trifasciata Hahnii',
        category: 'indoor',
        price: 400,
        image: 'images/products/sansevieria-compacta-k400.webp',
        badge: 'Budget Favorite',
        badgeColor: 'var(--verdant-accent)',
        light: 'Low to Bright Indirect',
        water: 'Every 14-20 Days',
        petFriendly: false,
        size: 'Compact (25cm)',
        description: 'Charming rosette snake plant variety that thrives on office desks and small windowsills with almost zero maintenance.',
        featured: false,
        tags: ['snake plant', 'dwarf', 'tabletop', 'low maintenance', 'air purifier', 'bedroom']
    }
];

// Global helper functions
window.VG_PRODUCTS = PRODUCTS;

function getProductById(id) {
    return PRODUCTS.find(p => p.id === id);
}

function formatPrice(price) {
    return 'K' + Number(price).toLocaleString('en-US');
}
